In [1]:
import numpy as np

### Creación de arrays

In [2]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [4]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [14]:
a = np.ones((3,2,3))

In [15]:
a

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

### Propiedades del array

In [16]:
# Número de elementos en cada dimensión
a.shape

(3, 2, 3)

In [17]:
# Longitud del array
a.ndim

3

In [18]:
# Elementos totales del array
a.size

18

### Otra forma de crear un array de numpy a través de listass de Python

In [19]:
l = [[1,2,3],[4,5,6]]
np.array(l)

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
# vector de 'int' en rango
np.arange(1,5)

array([1, 2, 3, 4])

In [21]:
# vector de 'float' en rango
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [23]:
# matriz de números aleatorios
np.random.rand(3,4)

array([[0.04746319, 0.84288616, 0.16512131, 0.65700701],
       [0.34849289, 0.21532456, 0.19393024, 0.26888222],
       [0.32461978, 0.69609161, 0.69152484, 0.08895712]])

In [24]:
# para acceder al tipo de datos del array
a.dtype

dtype('float64')

In [28]:
# Para indicar a NumPy el tipo de dato concreto con el que queremos trabajar
a = np.arange(1,5, dtype=np.float16)
a

array([1., 2., 3., 4.], dtype=float16)

### Cambiar la forma de un array para acomodarlo a ciertas operaciones

In [29]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
a2 = a.reshape(2,5)   # 2 rows - 5 columns
a2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

### Vectorización: Para realizar operaciones aritméticas entre arrays

In [33]:
a = np.array([14,23,3,21])
b = np.array([5,3,11,6])
a + b

array([19, 26, 14, 27])

In [34]:
a - b

array([ 9, 20, -8, 15])

In [35]:
a * b

array([ 70,  69,  33, 126])

In [36]:
a / b

array([2.8       , 7.66666667, 0.27272727, 3.5       ])

### Para acceder y modificar valores dentro de un array

In [37]:
a = np.array([1,5,3,19,13,7,3])
a

array([ 1,  5,  3, 19, 13,  7,  3])

In [38]:
a[3]

19

In [39]:
a[2:5]

array([ 3, 19, 13])

In [40]:
a[2:-1]

array([ 3, 19, 13,  7])

### Para indexar valores en matrices o tensores con más dimensiones

In [41]:
b = np.arange(48).reshape(4,12)
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47]])

In [42]:
# valor en segunda fila, tercera columna
b[1,2]

14

In [43]:
# valor en primera fila, primera columna
b[0,0]

0

### Indexado fancy, nos permite indexar un array mediante una lista con los índices de interés

In [44]:
# primera y tercera fila, desde la tercera columna a la cuarta
b[(0,2),2:4]

array([[ 2,  3],
       [26, 27]])

### Indexado booleano para trabajar con máscaras

In [45]:
a = np.array([1,2,3,4])
mask = np.array([True,False,True,False])
a[mask]

array([1, 3])

### Para iterar sobre un array de NumPy

In [46]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [47]:
for i in a:
    print(i)

0
1
2
3
4


### Para iterar con `arrays multidimensionales` necesitamos un loop por cada dimensión

In [48]:
a = np.arange(9).reshape((3,3))
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [49]:
for f in a:
    for c in f:
        print(c)

0
1
2
3
4
5
6
7
8


### Para guardar los arrays en nuestro disco, y luego cargarlos

In [51]:
a = np.random.rand(2,3)
a

array([[0.36481512, 0.62855772, 0.84343384],
       [0.77603595, 0.73579413, 0.52978265]])

In [52]:
# Para guardar el archivo
np.save('mi_array',a)

In [54]:
# Para cargar el archivo
b = np.load('mi_array.npy')
b

array([[0.36481512, 0.62855772, 0.84343384],
       [0.77603595, 0.73579413, 0.52978265]])