# 03_data_school_sklearn_select_columns

1. column name
2. integer position
3. slice
4. boolean mask
5. regex pattern
6. dtypes to include
7. dtypes to exclude

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import make_column_transformer, ColumnTransformer, make_column_selector
from sklearn.impute import SimpleImputer, KNNImputer

In [28]:
train = pd.read_csv(r'./dataset/train.csv', sep=';')
X = train.drop(['PassengerId','Survived','Pclass', 'Name', 'Ticket', 'SibSp', 'Parch', 'Ticket', 'Cabin'], axis=1)
X = X.iloc[5:10]
print(X.columns.tolist())

['Sex', 'Age', 'Fare', 'Embarked']


In [29]:
X = X[['Fare', 'Embarked', 'Sex', 'Age']] #.reset_index(inplace=True)
X

Fare Embarked     Sex   Age
5   8.4583        Q    male   NaN
6  51.8625        S    male  54.0
7  21.0750        S    male   2.0
8  11.1333        S  female  27.0
9  30.0708        C  female  14.0

In [30]:
a = make_column_transformer((OneHotEncoder(),['Embarked','Sex']))
a.fit_transform(X)

array([[0., 1., 0., 0., 1.],
       [0., 0., 1., 0., 1.],
       [0., 0., 1., 0., 1.],
       [0., 0., 1., 1., 0.],
       [1., 0., 0., 1., 0.]])

In [31]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 5 to 9
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Fare      5 non-null      float64
 1   Embarked  5 non-null      object 
 2   Sex       5 non-null      object 
 3   Age       4 non-null      float64
dtypes: float64(2), object(2)
memory usage: 292.0+ bytes


In [32]:
selectcolumn = [['Embarked','Sex'],
                [1,2],  # columnas 1 y 2
                slice(1,3), # columnas 1:'Embarked' hasta 2:'Sex' (Python cuenta desde 0 hasta n-1 )
                [False,True,True,False],  # boolean 
                make_column_selector(pattern='E|S'),  # nombres de columnas que contengan 'E' o 'S'
                make_column_selector(dtype_include = object),  # columnas tipo objeto
                make_column_selector(dtype_exclude = 'number')]  # columnas numéricas

In [33]:
for i in selectcolumn:
    ct = make_column_transformer((OneHotEncoder(), i))
    print(ct.fit_transform(X))
    print('-----------')

[[0. 1. 0. 0. 1.]
 [0. 0. 1. 0. 1.]
 [0. 0. 1. 0. 1.]
 [0. 0. 1. 1. 0.]
 [1. 0. 0. 1. 0.]]
-----------
[[0. 1. 0. 0. 1.]
 [0. 0. 1. 0. 1.]
 [0. 0. 1. 0. 1.]
 [0. 0. 1. 1. 0.]
 [1. 0. 0. 1. 0.]]
-----------
[[0. 1. 0. 0. 1.]
 [0. 0. 1. 0. 1.]
 [0. 0. 1. 0. 1.]
 [0. 0. 1. 1. 0.]
 [1. 0. 0. 1. 0.]]
-----------
[[0. 1. 0. 0. 1.]
 [0. 0. 1. 0. 1.]
 [0. 0. 1. 0. 1.]
 [0. 0. 1. 1. 0.]
 [1. 0. 0. 1. 0.]]
-----------
[[0. 1. 0. 0. 1.]
 [0. 0. 1. 0. 1.]
 [0. 0. 1. 0. 1.]
 [0. 0. 1. 1. 0.]
 [1. 0. 0. 1. 0.]]
-----------
[[0. 1. 0. 0. 1.]
 [0. 0. 1. 0. 1.]
 [0. 0. 1. 0. 1.]
 [0. 0. 1. 1. 0.]
 [1. 0. 0. 1. 0.]]
-----------
[[0. 1. 0. 0. 1.]
 [0. 0. 1. 0. 1.]
 [0. 0. 1. 0. 1.]
 [0. 0. 1. 1. 0.]
 [1. 0. 0. 1. 0.]]
-----------
